//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraningDataBase5TicG3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesionespersonas
    {
        public int id { get; set; }
        public Nullable<int> idPersonas { get; set; }
        public Nullable<int> idProfesiones { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual profesiones profesiones { get; set; }
    }
}
